# Generated by Django 3.1.4 on 2021-01-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_banner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link_url',
            field=models.URLField(default='', max_length=100, verbose_name='图片链接'),
        ),
    ]
