# Generated by Django 3.1.4 on 2021-01-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210107_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Science',
        ),
    ]
