# Generated by Django 3.1.4 on 2021-01-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_science'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link_url',
        ),
    ]
