# Generated by Django 3.1.4 on 2021-01-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_banner_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link_url',
            field=models.URLField(default='', max_length=100, verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_info',
            field=models.CharField(default='', max_length=50, verbose_name='标题'),
        ),
    ]
