# Generated by Django 3.1.4 on 2021-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210107_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.URLField(default='', verbose_name='图片链接'),
        ),
    ]
