# Generated by Django 3.1.4 on 2021-01-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210108_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.URLField(verbose_name='图片链接'),
        ),
    ]
